version: "3"

networks:
  nginx-php-db:

services:
  web:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/project
      - ./docker_dev/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - php
    networks:
      - nginx-php-db
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www/project
      - ./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - nginx-php-db
  db:
    image: mysql:5.7
    container_name: db-container
    environment:
      MYSQL_DATABASE: sharepad1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - nginx-php-db
  redis:
    image: redis
    container_name: redis-container
    networks:
      - nginx-php-db
    ports:
      - "6379:6379"
    command:
      - redis-server
  mercure:
    networks:
      - nginx-php-db
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./mercure/Caddyfile.dev:/etc/caddy/Caddyfile.dev
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
