name: Automated Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '7.4.0'
    - uses: actions/checkout@v4

    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create Database
      run: |
        php bin/console doctrine:schema:create
        php bin/console doctrine:migrations:migrate
        php bin/console doctrine:fixtures:load

    - name: Execute tests via PHPUnit
      env:
        DATABASE_URL: mysql://user:password@db:3306/sharepad?serverVersion=5.7.44-mysql
      run: vendor/bin/phpunit

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: npm encore production --progress
        start: npm encore dev
