name: Automated Tests

on: push

jobs:
  run-automated-tests:
    runs-on: ubuntu-22.04

    env:
      DB_DATABASE: sharepad
      DB_USER: root
      DB_PASSWORD: root
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/sharepad

    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: "8.2.12"
      - uses: actions/checkout@v4

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist
          npm ci

      - name: Create Database
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u"$DB_USER" -p"$DB_PASSWORD"
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=dev

      - name: Execute tests via PHPUnit
        run: |
          vendor/bin/phpunit
