name: Lint Code Base

on: push

jobs:
  run-lint:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: sharepad
      DB_USER: root
      DB_PASSWORD: root
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/sharepad

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer update --prefer-dist --no-progress --ignore-platform-req=php
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
